### ISSUE TITLE
OpenStack Security Groups - missing rule

### ISSUE THREAD

**Issue by cklause** [cloudfoundry/docs-deploying-cf#112]
Hi,

the documentation lists the following security group rule:

| Ingress   | IPv4       | TCP         | -          | cf (Security Gp) |

but no UDP counterpart. I think this is required for Consul to work.

| Ingress   | IPv4       | UDP         | -          | cf (Security Gp) |

[issue cf release](https://github.com/cloudfoundry/cf-release/issues/959)

**Comment by aduffeck** [comment]
:+1: 

We ran into a similar issue where we had to allow incoming UDP traffic on port 3457 from the security group so that doppler could receive log messages well.

**Comment by bentarnoff** [comment]
Hey @cklause did you determine whether the lack of a security group allowing incoming UDP traffic was the source of your problem? We can update the topic but we'd like to provide a more restricted security group if possible. The ports required by Consul are provided [here](https://www.consul.io/docs/agent/options.html#ports) and @aduffeck above indicated that incoming UDP traffic to port 3457 needs to be open for Doppler. Do you have anything more specific to add?

**Comment by bentarnoff** [comment]
We've updated the docs to correct this error. Thanks for bringing it to our attention. I'm closing this issue for now, but please feel free to get in touch in the future with any feedback.
