### ISSUE TITLE
bosh aws create is not a valid command

### ISSUE THREAD

**Issue by jadekler** [cloudfoundry/docs-deploying-cf#117]
Docs talk about this `bosh aws create` command:

https://github.com/cloudfoundry/docs-deploying-cf/blob/master/aws/cf-stub.html.md.erb#L75

That command does not exist:

```
 2016-06-29 09:35:16 ☆ |ruby-2.3.0| lawry in ~/jean-tmp/git-cf-mysql-bug
±  |master U:1 ?:2 ✗| → bosh aws create
Unknown command: aws create

 2016-06-29 09:35:18 ☆ |ruby-2.3.0| lawry in ~/jean-tmp/git-cf-mysql-bug
±  |master U:1 ?:2 ✗| → bosh version
BOSH 1.3232.0
```

**Comment by bentarnoff** [comment]
Thanks, @jadekler. To use `bosh aws create`, you must first install the BOSH CLI AWS plugin with `gem install bosh_cli_plugin_aws`, as discussed in our topic [Bootstrapping an AWS Environment for Cloud Foundry](https://docs.cloudfoundry.org/deploying/aws/setup_aws.html). I'm closing this for now but please don't hesitate to get in touch if you have any further feedback or concerns.
