### ISSUE TITLE
Docs on generating jwt/uaa keys are incomplete

### ISSUE THREAD

**Issue by neilhwatson** [cloudfoundry/docs-deploying-cf#127]
From http://docs.cloudfoundry.org/deploying/common/vsphere-vcloud-cf-stub.html

> Generate a PEM-encoded RSA key pair, and replace JWT_SIGNING_KEY with the private key, and JWT_VERIFICATION_KEY with the corresponding public key.
> Paste in the full keys, including the BEGIN and END delimiter lines. 

Please improve this documentation. I've been struggling for days guessing on what this key pair is and how to generate it and every guess is wrong.

**Comment by bentarnoff** [comment]
Hey @neilhwatson you can generate a PEM-encoded RSA key pair from the command line with `ssh-keygen`. You can use the procedures outlined [here](https://docs.cloudfoundry.org/running/config-ssh.html#requirements). Please let us know if that helps resolve your issue.

**Comment by neilhwatson** [comment]
@bentarnoff Yes, I did end up trying ssh, but not because I associated the link you provided with the install procedure. Merely trial and error. A better explanation on or linked from the install page would be welcome.

**Comment by bentarnoff** [comment]
@neilhwatson We'll make sure to update the topic with a better explanation of how to generate a key pair. I'm closing this for now, but please feel free to get in touch in the future if you have any further feedback.
