### ISSUE TITLE
dea_next resources too small in Vsphere install doc

### ISSUE THREAD

**Issue by neilhwatson** [cloudfoundry/docs-deploying-cf#130]
This doc: http://docs.cloudfoundry.org/deploying/common/vsphere-vcloud-cf-stub.html has a stub that the user is supposed to edit. Specifically this part:

  dea_next:
    disk_mb: 2048
    memory_mb: 1024

That number is too small. The default staging numbers provided by cf-release are:
    staging_disk_limit_mb: 6144
    staging_memory_limit_mb: 1024

This check:
https://github.com/cloudfoundry/cloud_controller_ng/blob/1b748b49d93157cd5f267f9a57c727b3fffaa91f/lib/cloud_controller/dea/pool.rb#L97

Will fail because staging_disk_limit_mb is greater than disk_mb and any pushed app will not start.

**Comment by ljarzynski** [comment]
Hi @neilhwatson! Thanks for pointing this out, seems like it will save our readers some trouble. We at docs can't actually change that, as we pull in that stub from cf release. Might I suggest PR'ing that file? https://github.com/cloudfoundry/cf-release/blob/master/spec/fixtures/vsphere/cf-stub.yml.
