### ISSUE TITLE
metron agent cannot collect logs of the apps

### ISSUE THREAD

**Issue by fairychild1** [cloudfoundry/docs-deploying-cf#135]
OpenStack Security Groups - missing rule , the udp port 3457 should be open, because metron agent send and collect information with this port. if this port is closed, the doppler cannot get the logs of the apps.

**Comment by bentarnoff** [comment]
Thanks, @fairychild1. We've corrected this topic on our staging site, and it should be viewable on our production site soon. I'm closing this issue for now but please feel free to be in touch in the future with any additional feedback.
