### ISSUE TITLE
Update/remove reference to `.ruby-version`

### ISSUE THREAD

**Issue by mcwumbly** [cloudfoundry/docs-deploying-cf#136]
In the **Create a Manifest** doc it says:

> Install the Ruby version listed in the `.ruby-version` file of the cf-release repository. You can manage your Ruby versions using `rvm`, `rbenv`, or `chruby`

https://github.com/cloudfoundry/docs-deploying-cf/blob/master/boshlite/create_a_manifest.html.md.erb#L64

But the `.ruby-version` file was recently removed:

https://github.com/cloudfoundry/cf-release/issues/1025

Should this line just be delete from the docs or changed to say something about the last known working ruby version? /cc @Amit-PivotalLabs

**Comment by Amit-PivotalLabs** [comment]
Thanks for the catch @mcwumbly, we should remove that line.  Gonna move the tracker story to a different icebox /cc @animatedmax @dsabeti

**Comment by jaresty** [comment]
Created [pull request](https://github.com/cloudfoundry/docs-deploying-cf/pull/138)

**Comment by animatedmax** [comment]
Thanks!
