### ISSUE TITLE
Build the Cloud Foundry Release Failed

### ISSUE THREAD

**Issue by Ynull** [cloudfoundry/docs-deploying-cf#137]
When I go to the step2(http://docs.cloudfoundry.org/deploying/common/deploy.html), which is 'Build the Cloud Foundry Release', run 'bosh create release' then I get the result below:
```
Building collector...
  No artifact found for collector
  Generating...
  Pre-packaging...
  > + set -e $'-x\r'
: invalid optiong: line 1: set: -
  > set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
  > + $'\r'
  > pre_packaging: line 2: $'\r': command not found
  > + cd $'/tmp/d20160927-2162-c8vdwp/d20160927-2162-cgzkck/collector\r'
: No such file or directorycd: /tmp/d20160927-2162-c8vdwp/d20160927-2162-cgzkck/collector
  > + BUNDLE_WITHOUT=development:test
  > + bundle package --all --no-install --path $'./vendor/cache\r'
  > Could not locate Gemfile
  > + rm -rf $'./vendor/cache/ruby\r'
  > + rm -rf $'./vendor/cache/vendor\r'
  > + bundle config --delete $'NO_INSTALL\r'
  > + $'\r'
  > pre_packaging: line 8: $'\r': command not found
'collector' pre-packaging failed
```
my env is windows7 x64, deploy on BOSH-Lite, what should I do?

**Comment by ljarzynski** [comment]
Hello @Ynull! Thank you for your submission. Unfortunately, the documentation team is not equipped to help troubleshoot errors with your deployment. I think this question is more appropriate for either the cf-release repository or the release engineering channel on cloudfoundry.slack.com. If you find the answer and discover that there was a mistake in our documentation, please feel free to submit a pull request with the update. Thanks!
