### ISSUE TITLE
docs-deploying-cf/blob/master/common/deploy.html.md.erb ubuntu not specified as necessary

### ISSUE THREAD

**Issue by lv2program** [cloudfoundry/docs-deploying-cf#144]
The instruction for choosing a stemcell says to choose one from bosh.io/stemcells however the bosh deploy command is specifically looking for the warden ubuntu stemcell. May want to clarify this. Specifically i chose centos and it failed as the cf files defaulted in the example of the cf-release project specifically called for the ubuntu trusty stemcell.

**Comment by bentarnoff** [comment]
Hey @lv2program thanks for bringing this to our attention. We've updated the topic to specify that users must download an Ubuntu Trusty stemcell. You can see the change on our staging site (https://docs-cloudfoundry-staging.cfapps.io/deploying/common/deploy.html) but it will also be viewable on our production site soon. I'm closing this issue but please feel free to get in touch if you have further feedback.
