### ISSUE TITLE
Unclear instructions for installing spiff

### ISSUE THREAD

**Issue by isartcanyameres** [cloudfoundry/docs-deploying-cf#145]
The guide does not specify required actions to install spiff. 
It provides a link to the spiff readme ([here](https://github.com/cloudfoundry/docs-deploying-cf/blob/master/boshlite/create_a_manifest.html.md.erb#L65)) which does not provide clear instructions either.

I'm missing which spiff architecture bosh-lite expects, between those available as [spiff releases](https://github.com/cloudfoundry-incubator/spiff/releases/tag/v1.0.7) (darwin or linux)

I'm also missing how to install downloaded binary. Although this would better fit in [spiff install instructions](https://github.com/cloudfoundry-incubator/spiff#installation).
`chmod +x` is probably a must here, but I don't know where to place it so next instructions find it.

**Comment by bentarnoff** [comment]
Hi @isartcanyameres. 

Spiff is a command line tool for generating manifests. You should download the Spiff release that will run on your local machine. If you're on a Mac, download the Darwin release. If you're on Linux, download the Linux release. 

The downloaded file will either be a binary or a zipped binary. If it's zipped, unzip it. Then place the binary in your path. It might require a `chmod`, although I just tried and it didn't require it. (I'm on a Mac, so I downloaded the Darwin release.)

Hope this helps. I'm closing the issue, but please don't hesitate to get in touch with any further questions.

**Comment by isartcanyameres** [comment]
Thank you so much for your answer.
It's been fast, well defined and written in a manner that I'm glad to read. I appreciate it.
Thank you again! :)
