### ISSUE TITLE
bosh aws create is no longer a valid option these docs need updating

### ISSUE THREAD

**Issue by duncwinn** [cloudfoundry/docs-deploying-cf#148]
bosh aws create is not a recognized bosh command

**Comment by ljarzynski** [comment]
@duncwinn Thanks for bringing this to our attention! Would you be able to help us document the alternative way to set up your AWS environment for CF before deploying? Or perhaps docs should get in touch with Release Integration?

**Comment by cf-pub-tools** [comment]
Blocked on https://www.pivotaltracker.com/n/projects/1488988/stories/135991861

**Comment by animatedmax** [comment]
[Preparing to Deploy on Amazon Web Services](http://docs.cloudfoundry.org/deploying/aws/index.html)
[Deploying BOSH on AWS](http://docs.cloudfoundry.org/deploying/aws/setup_bosh_aws.html)
[Customizing the Cloud Foundry Deployment Manifest for AWS](http://docs.cloudfoundry.org/deploying/aws/cf-stub.html)
[Deploying Cloud Foundry on AWS](http://docs.cloudfoundry.org/deploying/aws/deploy-aws.html)
