### ISSUE TITLE
Missing 'loggregator' section in cf-stub template

### ISSUE THREAD

**Issue by mcpeak** [cloudfoundry/docs-deploying-cf#152]
The template for cf-stub misses a section for 'loggregator' that seems to be required to run bosh deploy successfully.  Maybe this is new since the guide was written?

Regardless, I couldn't progress without adding this example manifest: https://github.com/cloudfoundry/loggregator#example-manifest  (and generating keys, certs, etc using the script for loggregator).

**Comment by pspinrad** [comment]
Hey @mcpeak -- are you saying that the Loggregator example manifest code chunk, with tls certs and keys should be in all the cf-stub.yml files here: https://github.com/cloudfoundry/cf-release/tree/master/spec/fixtures ?  Thanks!

**Comment by mcpeak** [comment]
@pspinrad Either that or we can update documentation to show how to insert this information in another location.  Maybe I have it wrong but was blocked on deploying my OpenStack cloud until I did this.

**Comment by jtarchie** [comment]
@mcpeak && @pspinrad, we've corrected the issue on cf-release [develop](https://github.com/cloudfoundry/cf-release/commit/bd4d8fae29aa77529bac8bef3563ffff6a9af8a5). Please let us know if that resolves your issue.

**Comment by jncd** [comment]
@jtarchie I think it will — just needs to be ported to master too so that it will publish in the docs!
