### ISSUE TITLE
Description why I should blacklist log drains is hard to understand

### ISSUE THREAD

**Issue by wolfoo2931** [cloudfoundry/docs-deploying-cf#153]
According to the description in log_drain_blacklists.html.md.erb I'm not able to fully understand the use case of the configuration. 

> The doppler component allows application log drains. An application developer deploying their app to Cloud Foundry can bind a drain to a log analysis service.

- Are you referring to the `cf bind-service -l ...` feature? I guess you do but I'm not sure. 

> The performance of your Cloud Foundry installation can be affected if the application developer attempts to bind a drain to an internal Cloud Foundry component.

- Why should a developer try to bind a logdrain to a Cloud Foundry component and which Cloud Foundry component would make sense to bind a drain to?
- How/Why does it affect the performance?

**Comment by ljarzynski** [comment]
@wolfoo2931 Thanks for filing this issue. The topic could definitely use some attention. I'll contact the appropriate subject matter experts and update the document accordingly. Will reach back out to you once we publish.

**Comment by bentarnoff** [comment]
Hey @wolfoo2931 we've updated the "Log Drain Blacklist Configuration" topic with a bit more information. You can see the topic on our staging site at the following address: https://docs-cloudfoundry-staging.cfapps.io/deploying/common/log_drain_blacklists.html. I hope this addresses your concerns. I'm closing this issue for now but please feel free to respond if you have further feedback.
