### ISSUE TITLE
Explanation of UAA certs is missing from most IaaS stubs

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry/docs-deploying-cf#161]
Similar to https://github.com/cloudfoundry/docs-deploying-cf/issues/160, I've noticed that only some of the IaaS docs explain these properties. Specifically, [this explanation](https://github.com/cloudfoundry/docs-deploying-cf/blob/master/azure/cf-stub.html.md.erb#L309-L316) should provided in all of the IaaS stubs.

If we didn't have [cf-deployment](https://github.com/cloudfoundry/cf-deployment) on the way, I'd suggest consolidating the part of these docs that are IaaS-agnostic. I'll be sure to help out with documentation of cf-deployment as it gets closer.

cc @sreetummidi @fhanik

**Comment by animatedmax** [comment]
Thanks, @dsabeti We've added the `sslCertificate` and `sslPrivateKey` explanation you suggested to all the IaaS stub topics. (We're still working on https://github.com/cloudfoundry/docs-deploying-cf/issues/160)
