### ISSUE TITLE
Explanation of `saml` configuration is missing from most IaaS stubs

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry/docs-deploying-cf#166]
Hey there!

It looks like the Azure docs [explain how to generate the full `saml` configuration for the UAA](https://github.com/cloudfoundry/docs-deploying-cf/blob/master/azure/cf-stub.html.md.erb#L352-L364), but most other IaaS docs don't. The information for this is independent of IaaS, so it should be present in all the docs.

**Comment by animatedmax** [comment]
Thank you @ctaymor and @dsabeti
