### ISSUE TITLE
multiple typos in examples - deploy-aws.html.md.erb

### ISSUE THREAD

**Issue by magnetnoc** [cloudfoundry/docs-deploying-cf#171]
Dashes where they shouldn't be caused several issues:

bosh upload-stemcell    
   - produces an error: Unknown command: upload-stemcell
   - should be: bosh upload stemcell   

bosh create-release
   - produces an error: Unknown command: create-release
   - should be: bosh create release

bosh upload-release
   - produces an error: Unknown command: upload-release
   - should be: bosh upload release

The 'Deploy Cloud Foundry' step also failed:

 bosh -d cf deploy ../cf-deployment.yml
   - produces an error:   wrong number of arguments (given 1, expected 0).
                                       Usage: deploy [--recreate] [--no-redact] [--skip-drain [job1,job2]]

I'm still researching the correct command here - suggestions are welcome

**Comment by pspinrad** [comment]
Maybe the issue is BOSH CLI version-- BOSH CLI v2 commands have dashes, like `upload-stemcell`, `create release`, etc.
https://bosh.io/docs/cli-v2.html

...whereas analogous BOSH CLI v1 commands were like `bosh upload stemcell` etc., without dashes.

**Comment by magnetnoc** [comment]
OK, that makes sense, as I am using bosh 1 - maybe that should be indicated somewhere, or perhaps the examples could include both bosh 1 + bosh 2 examples?

**Comment by pspinrad** [comment]
Great-- yeah, good idea to note both-- the bosh docs also show a lot of v1-style examples.  Sorry for the lack of clarity!

**Comment by magnetnoc** [comment]
I guess I'll close this then - thanks for your response.

**Comment by pspinrad** [comment]
Cool-- happy to help
