### ISSUE TITLE
docs-deploying-cf/blob/master/aws/setup_bosh_aws.html.md.erb --where's the manifest?

### ISSUE THREAD

**Issue by tomsherrod** [cloudfoundry/docs-deploying-cf#172]
In the doc: https://github.com/cloudfoundry/docs-deploying-cf/blob/master/aws/setup_bosh_aws.html.md.erb   
Under Overview:
4. A copy of the manifest you use to deploy the BOSH Director.
Where's this manifest located?

Tom

**Comment by cf-pub-tools** [comment]
Hi @tomsherrod 

This documentation repository is maintained by technical writers, not developers or support engineering. 

If you have questions about the open source Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list.

For questions about Pivotal Cloud Foundry, please contact Pivotal support: https://support.pivotal.io

Thank you.
