### ISSUE TITLE
CF deployment on BOSH lite failing

### ISSUE THREAD

**Issue by subhankarc** [cloudfoundry/docs-deploying-cf#176]
Deployment on bosh-lite is not working if I follow the steps mentioned in [here](http://docs.cloudfoundry.org/deploying/boshlite/create_a_manifest.html)

I used cf-271 release as well as cf-260 release but none of them works. The deployment fails as the consul_z1 is not running after update.

I ssh into the vm and see the following logs.

```
error during stop: dial tcp [::1]:8400: getsockopt: connection refused
error during start: timeout exceeded: "rpc error: failed to get conn: x509: certificate has expired or is not yet valid"
2017/08/09 04:23:24 [ERR] agent.client: Failed to decode response header: EOF
2017/08/09 04:23:24 [ERR] agent.client: Failed to decode response header: EOF
error during start: timeout exceeded: "rpc error: failed to get conn: x509: certificate has expired or is not yet valid"
2017/08/09 04:24:26 [ERR] agent.client: Failed to decode response header: EOF
2017/08/09 04:24:26 [ERR] agent.client: Failed to decode response header: EOF
error during start: timeout exceeded: "rpc error: failed to get conn: x509: certificate has expired or is not yet valid"
```

Looks like there is some certificate generation steps missing or the certificates are invalid. Can you please help?

Also, should we use cf-deployment for development and testing purposes?

**Comment by seviet** [comment]
hi @subhankarc! i'm so sorry you're having problems with your BOSH lite deployment. i would suggest asking for help in the Cloud Foundry Slack http://cloudfoundry.slack.com (#cf-users channel might be a good option). RE: cf-deployment, yes-- according to this table https://github.com/cloudfoundry/cf-deployment#readiness it is ready for dev and testing purposes!
