### ISSUE TITLE
Why are such large disk sizes required? (instance flavors for CF on OpenStack)

### ISSUE THREAD

**Issue by wildloop** [cloudfoundry/docs-deploying-cf#179]
In this doc [docs-deploying-cf/openstack/required-flavors.html.md.erb](http://docs.cloudfoundry.org/deploying/openstack/required-flavors.html) is written:

> [...] flavors must have the following listed specifications, at minimum:
>
> Flavor Name | VCPUs | RAM (GB) | Root Disk (GB) | Ephemeral Disk (GB)
> -------------- | ------ | ----------- | ---------- | -------------------- 
> m1.small | 1 | 2 | 10 | 20
> m1.medium | 2 | 4 | 10 | 40
> m1.large | 4 | 8 | 10 | 80
> m1.xlarge | 8 | 16 | 10 | 160
>

I found that when I reduce flavors disk sizes to these values:

Flavor Name | VCPUs | RAM (GB) | Root Disk (GB) | Ephemeral Disk (GB)
-------------- | ------ | ----------- | ---------- | -------------------- 
m1.small | 1 | 2 | 4 | 4
m1.medium | 2 | 4 | 4 | 8
m1.large | 4 | 8 | 4 | 16
m1.xlarge | 8 | 16 | 4 | 32

then instances disks usage in my deployment look like this (`bosh instance --ps`):

Instance | RAM Usage | Swap Usage | System Disk Usage | Ephemeral Disk Usage | Persistent Disk Usage
--- | --- | --- | --- | --- | ---
api_z1 | 10% (838MB) | 0% | 29% (23i%) | 6% (5i%) | -
blobstore_z1 | 3% (134MB) | 0% | 29% (23i%) | 3% (1i%) | 0% (0i%)
clock_z1 | 7% (290MB) | 0% | 29% (23i%) | 12% (10i%) | -
consul_z1 | 5% (95MB) | 0% | 29% (23i%) | 5% (3i%) | 0% (0i%)
doppler_z1 | 4% (142MB) | 0% | 29% (23i%) | 4% (1i%) | -
etcd_z1 | 2% (168MB) | 0% | 29% (23i%) | 2% (1i%) | 0% (0i%)
ha_proxy_z1 | 3% (117MB) | 0% | 29% (23i%) | 3% (1i%) | -
loggregator[...]_z1 | 5% (100MB) | 0% | 29% (23i%) | 6% (3i%) | -
nats_z1 | 3% (109MB) | 0% | 29% (23i%) | 3% (1i%) | -
postgres_z1 | 3% (140MB) | 0% | 29% (23i%) | 4% (3i%) | 2% (1i%)
router_z1 | 3% (114MB) | 0% | 29% (23i%) | 3% (2i%) | -
stats_z1 | 6% (125MB) | 0% | 29% (23i%) | 13% (6i%) | -
uaa_z1 | 18% (711MB) | 0% | 29% (23i%) | 13% (2i%) | -

Why are such large disk sizes required by default?
Doesn't it slow down IaaS operations?

**Comment by cf-pub-tools** [comment]
Hi @wildloop 

This documentation repository is maintained by technical writers, not developers or support engineering. 

If you have questions about the open source Cloud Foundry project, we recommend that you contact the cf-dev@lists.cloudfoundry.org mailing list.

For questions about Pivotal Cloud Foundry, please contact Pivotal support: https://support.pivotal.io

Thank you.

**Comment by wildloop** [comment]
Thanks,
There are the flavors with the new names and configuration (cf-deployment):
https://github.com/cloudfoundry/cf-deployment/tree/master/iaas-support/openstack
