### ISSUE TITLE
Deployment instructions need updating?

### ISSUE THREAD

**Issue by jtdice** [cloudfoundry/docs-deploying-cf#182]
The current page on creating a deployment manifest for CloudFoundry references precursor steps as installing BOSH-Lite and BOSH CLI.  The linked instructions on bosh.io then have you install CLI v2 ... but the deployment manifest instructions reference BOSH CLI v1 instructions such as "bosh target", as does the generate-bosh-lite-dev-manifest script.  Am I missing something, do I need to run this activity using BOSH CLI v1, or does the project need to be updated for CLI v2 command set?

**Comment by animatedmax** [comment]
Hi @jtdice As you noted, the documentation needed to be updated with the new BOSH CLI v2 commands. We have updated documentation throughout the site with these new BOSH CLI v2 commands. Thank you for helping us keep the documentation up-to-date.

**Comment by jtdice** [comment]
@animatedmax The cf-release scripts *also* need to be updated, specifically generate-bosh-lite-dev-manifest.  Still references cli v1 commands like status.
