### ISSUE TITLE
How to deploy to GCP?

### ISSUE THREAD

**Issue by tscolari** [cloudfoundry/docs-deploying-cf#187]
There's a gap around how to deploy cf to gcp:

https://docs.cloudfoundry.org/deploying/cf-release/index.html

I would contribute with this, but I honestly don't know how to do it. 
My team always lose days every time we need a new cf deployed.

**Comment by seviet** [comment]
Hey @tscolari! Now that cf-deployment is GA, I would recommend using cf-deployment instead to deploy to GCP. 
https://docs.cloudfoundry.org/deploying/cf-deployment/index.html
We will be deprecating the cf-release docs.
