### ISSUE TITLE
How to get the cert files given in the command

### ISSUE THREAD

**Issue by srinivas-kandula** [cloudfoundry/docs-deploying-cf#195]
We are following steps given in the step 4: "Create Infrastructure, Bastion, BOSH Director, and Load Balancers". The plan command is refering to "YOUR-CERT.crt" and "YOUR-KEY.key" but doesn't tell steps on how to get those files.  It would be great if the steps are eloborated on getting those files.

**Comment by mlimonczenko** [comment]
Hello @srinivas-kandula,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
