### ISSUE TITLE
I Keep Exceeding my Quota. How many VMs do I Need to Deploy CF

### ISSUE THREAD

**Issue by tahteche** [cloudfoundry/docs-deploying-cf#197]
I am following the [instructions to deploy CF on GCP](https://docs-cloudfoundry-staging.cfapps.io/deploying/cf-deployment/deploy-cf.html) but the deployment fails because I am exceeding my quota (24 VMs). I doubled my CPU quota to 48 VMs and it still fails with the new limit. Will be nice to know the number of VMs needed so that I can just go for it. The error is as shown below:

```
Error: CPI error 'Bosh::Clouds::VMCreationFailed' with message 'VM failed to create: 
googleapi: Error 403: Quota 'CPUS' exceeded. 
Limit: 48.0 in region us-east1., quotaExceeded' in 'create_vm' CPI method
```

**Comment by mlimonczenko** [comment]
Hello @tahteche,

We were unable to prioritize this request at the time the issue was filed.

If this issue is still relevant, submit a new pull request (preferred) or a new GitHub issue.

I am closing this request. Thank you so much for your contribution.
