### ISSUE TITLE
Copy the following policy text to your clipboard:

### ISSUE THREAD

**Issue by antopraveen** [cloudfoundry/docs-deploying-cf#202]
Can you please let me know how to do this 

"Copy the following policy text to your clipboard:" , it is under Step 3: Create an IAM User

i am facing the below issue while executing 

$ aws iam put-user-policy --user-name "bbl-user" \
--policy-name "bbl-policy" \
--policy-document "$(pbpaste)"

Issue:
------

bash: command substitution: line 270: syntax error near unexpected token `)'
bash: command substitution: line 270: `pbpaste)"'

**Comment by ksummersill2** [comment]
I was able to correct his issue by creating a text file and running fill://<path to file>
