### ISSUE TITLE
Documentation for deploying BOSH on AWS - Step 1 is not longer required

### ISSUE THREAD

**Issue by cortega-lh** [cloudfoundry/docs-deploying-cf#209]
The step 1 is not longer required, the terraform scripts for deploying BOSH on AWS are already creating and using the hosted zones configured in this step.

https://github.com/cloudfoundry/docs-deploying-cf/blob/master/common/aws.html.md.erb#L34:L51

**Comment by cshollingsworth** [comment]
Hi, @cortega-lh ,

This topic has been updated to better reflect the current process.
