### ISSUE TITLE
Linked windows ops file is outdated

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/docs-deploying-cf#213]
https://github.com/cloudfoundry/docs-deploying-cf/blob/26f1fbf3240e810ea0e37da2d87ec957e2c942ff/cf-deployment/deploy-cf.html.md.erb#L40

The `windows-2016cell.yml` ops file has been removed and replaced with the [`windows-2019cell.yml`](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/windows2019-cell.yml).

**Comment by mjgutermuth** [comment]
Thank you for pointing this out, @ctlong! I've updated the link to point to the new ops file: https://docs.cloudfoundry.org/deploying/cf-deployment/deploy-cf.html#ops-files
