### ISSUE TITLE
Spiff only instructs on OSX installation

### ISSUE THREAD

**Issue by thetrav** [cloudfoundry/docs-deploying-cf#39]
http://docs.cloudfoundry.org/deploying/openstack/install_cf_openstack.html instructs to install Spiff, and links to the repo: https://github.com/cloudfoundry-incubator/spiff

However the instructions to install spiff rely on homebrew, which is only available on OSX.

My client is not running OSX, it's running ubuntu.

**Comment by kimahoff** [comment]
It looks like there are now instructions for installing Spiff via Linux at the repo link. We also have removed most Spiff-specific information from the docs, and have additional planned updates to this section.
