### ISSUE TITLE
bosh aws bootstrap suggests EOL ruby version.

### ISSUE THREAD

**Issue by mavenraven** [cloudfoundry/docs-deploying-cf#52]
https://github.com/cloudfoundry/docs-deploying-cf/blob/master/ec2/bootstrap-aws-vpc.html.md.erb says to use 1.9.3.

**Comment by animatedmax** [comment]
HI mavenraven,
The bosh_cli_plugin_aws.gemspec states a required ruby_version of '>= 1.9.3', but we've modified the documentation to let people know they can use a Ruby higher version. Thanks!
