### ISSUE TITLE
Instructions for deploying with bosh-lite (warden) and script syntax seem not to match

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/docs-deploying-cf#59]
The current bosh-lite deployment instructions for a local machine (which I assume to be for a warden-based deployment) state that you need to generate a stub containing the director UUID, but cf-release/scripts/generate-bosh-lite-dev-manifest contains this code:

    BOSH_STATUS=$(bosh status)
    EXPECTED_DIRECTOR_NAME="Bosh Lite Director"

    if [[ "$(echo "$BOSH_STATUS" | grep Name)" != *"$EXPECTED_DIRECTOR_NAME"* ]]; then
      echo "Can only target $EXPECTED_DIRECTOR_NAME. Please use 'bosh target' before running this script."
      exit 1
    fi

    mkdir -p "${CF_RELEASE_DIR}/bosh-lite/deployments"

    DIRECTOR_UUID=$(echo "$BOSH_STATUS" | grep UUID | awk '{print $2}')

When I pass a manifest stub into the script as directed by the docs, I get an error.  The old method I was using before of calling the script with no args still seems to work correctly.

**Comment by animatedmax** [comment]
Hi ScarletTanager,

The deployment instructions appear to be correct, although there is a bit of ambiguity. I'm changing the wording to make it clearer that you need to replace "DIRECTOR-UUID" in the manifest stub with your BOSH Director UUID. Example:

If the `bosh status --uuid` command returns `b02f8ab5-b63c-4f08-b144-89f96810a022`, your manifest stub should look like this:
```
---
director_uuid: b02f8ab5-b63c-4f08-b144-89f96810a022
```

I hope this solves the issue you've reported. If not, what error message are you seeing?

**Comment by animatedmax** [comment]
Updated documentation for clarity https://www.pivotaltracker.com/story/show/104443942
