### ISSUE TITLE
Links to IaaS-specific landing pages don't show me in sidenav

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/docs-deploying-cf#80]
On the main landing page for these docs, there are links for the instructions for each of the IaaSes.  E.g. there's `(aws/index.html)`.  When I click it, my URL doesn't have the `index.html`, it's just `/aws` at the end, and so the sidenav doesn't show where I am.  If I manually add `/index.html` to the end of the URL, I see where I am in the sidenav.

**Comment by animatedmax** [comment]
Resolved 23 Feb 2016 
https://github.com/pivotal-cf/docs-layout-repo/commit/dc195061bc353eeeda5e4465e61e2d7059d03ea7
