### ISSUE TITLE
Docs on filling out cf-stub should clarify non-overlapping requirements for domain, system_domain, and apps_domains

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/docs-deploying-cf#86]
I don't actually know what the real requirements are to pass the validations in Cloud Controller, but it would be nice if the docs guided users to not misconfiguring these domains so they can avoid the validation errors that only surface late at deploy time.

This is related to this issue: https://github.com/cloudfoundry/cloud_controller_ng/issues/552

(This issue was driven out by these stories: https://www.pivotaltracker.com/story/show/114144105, https://www.pivotaltracker.com/story/show/85293086)

**Comment by bentarnoff** [comment]
Thanks, @Amit-PivotalLabs. We've updated the "Customizing the Cloud Foundry Deployment Manifest Stub for AWS" topic in our docs.

**Comment by giner** [comment]
The documentation now covers system_domain and app_domain however one thing is still missing which is "domain". What is "domain" used for?
